### ISSUE TITLE
Class 'zxbodya\yii2\tinymce' not found

### ISSUE THREAD

**Issue by croatiangrn** [zxbodya/yii2-tinymce#2]
Can you suggest how to fix this?

**Comment by zxbodya** [comment]
there is no such class in extension... how did you got this error?

**Comment by croatiangrn** [comment]
I installed your extension, and assumed that this is the right way to use it:

use zxbodya\yii2\tinymce;

**Comment by zxbodya** [comment]
It should be `use zxbodya\yii2\tinymce\TinyMce;`

… `zxbodya\yii2\tinymce` is just namespace, but you need widget class from it

**Comment by croatiangrn** [comment]
Thank you!
